@Server_HostAddress = http://localhost:5172

GET {{Server_HostAddress}}/weatherforecast/
Accept: application/json

###

GET {{Server_HostAddress}}/slime/
Accept: application/json

###

POST {{Server_HostAddress}}/postslime/
ACCEPT: application/json

###