@Server_HostAddress = http://localhost:5172


GET {{Server_HostAddress}}/slime/2
Accept: application/json

###

GET {{Server_HostAddress}}/slime/market/
Accept: application/json

###

POST {{Server_HostAddress}}/api/user/earn/
Accept: application/json
Content-Type: application/json

{
  "userid": 0
}
###


POST {{Server_HostAddress}}/api/slime/update/
Accept: application/json
Content-Type: application/json

{
  "slime": [

    id: 0,
    name: "Gloob",
    svg: "",
    size: 3,
    colour: "blue",
    age: 2,
    isOnMarket: true,
    price: 3000,
    ownerId: 0
  ]
}


###

GET {{Server_HostAddress}}/api/user/
ACCEPT: application/json

###


POST {{Server_HostAddress}}/user/login/
ACCEPT: application/json
Content-Type: application/json

{
  "Username": "johnny151",
  "Password": "password123",
  "Email": ""
}

###