name: Build and Deploy .NET

on:
  push:
    branches:
        - main
    paths:
        - 'Server/**'
        - '.github/workflows/deploy-dotnet.yml'

env:
  DIR: Server
  S3BUCKET: slimekeeper-server
  ELASTIC_BEANSTALK_NAME: slimekeeper
  ELASTIC_BEANSTALK_ENV_NAME: slimekeeper-env


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4.2.2
        name: Checkout Repository

      - name: Setup .NET
        uses: actions/setup-dotnet@v4.3.0
        with:
            dotnet-version: '9.0.x'
        
      - name: Restore dependencies
        run: dotnet restore ${{ env.DIR }}/
        
      - name: Build
        run: dotnet build --no-restore ${{ env.DIR }}/
        
      - name: Test
        run: dotnet test ${{ env.DIR }}/

      - name: Pack
        run: |
          dotnet publish ${{ env.DIR }}/ -c Release --output "${{ github.workspace }}/${{github.run_id}}"
          cd ${{github.run_id}}
          zip -r ../${{github.run_id}}.zip .

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4.3.3
        with: 
          name: deploy-files
          path: ${{github.run_id}}.zip
  
  
  deploy:
    runs-on: ubuntu-latest
    needs: build
    
    steps:
      - uses: actions/download-artifact@v4.1.7
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4.1.0
        with:
          aws-region: ${{ secrets.AWS_REGION }}
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    
      - name: Deploy
        run: |
          aws s3 cp "deploy-files/${{github.run_id}}.zip" s3://elasticbeanstalk-${{ secrets.AWS_REGION }}-${{ secrets.AWS_ACCOUNT_ID }}/artifact/SlimeKeeper/
          aws elasticbeanstalk create-application-version --application-name $ELASTIC_BEANSTALK_NAME --version-label ${{github.run_id}} --description ${{github.run_id}} --source-bundle S3Bucket="elasticbeanstalk-${{ secrets.AWS_REGION }}-${{ secrets.AWS_ACCOUNT_ID }}",S3Key="artifact/SlimeKeeper/${{github.run_id}}.zip"
          aws elasticbeanstalk update-environment --application-name $ELASTIC_BEANSTALK_NAME --environment-name $ELASTIC_BEANSTALK_ENV_NAME --version-label ${{github.run_id}}
          aws elasticbeanstalk wait environment-updated --application-name $ELASTIC_BEANSTALK_NAME --environment-name $ELASTIC_BEANSTALK_ENV_NAME
