name: Build and Deploy React

on:
  push:
    branches:
        - main


env:
  applicationfolder: Client
  S3BUCKET: slimekeeper-client


jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4.2.2

      - name: Set up Node.js
        uses: actions/setup-node@v4.2
        with:
          node-version: 20.13.1

      - name: Install dependencies
        working-directory: ${{ env.applicationfolder }}/
        run: npm install

      - name: Build the project
        working-directory: ${{ env.applicationfolder }}/
        run: npm run build
        
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4.1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}
        
      - name: Upload to AWS S3
        working-directory: ${{ env.applicationfolder }}/
        run: aws s3 sync dist s3://${{ env.S3BUCKET }}/