name: Build and Deploy

on:
  push:
    branches:
      - main

env:
  DIR: Server

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4.2.2
        name: Checkout Repository

      - name: Setup .NET
        uses: actions/setup-dotnet@v4.3.0
        with:
            dotnet-version: '9.0.x'
        
      - name: Restore dependencies
        run: dotnet restore ${{ env.DIR }}/
        
      - name: Build
        run: dotnet build --no-restore ${{ env.DIR }}/
        
      - name: Test
        run: dotnet test ${{ env.DIR }}/

      - name: Pack
        run: |
          dotnet publish ${{ env.DIR }}/ -c Release --output "${{ github.workspace }}/${{github.run_id}}"
          cd ${{github.run_id}}
          zip -r ../${{github.run_id}}.zip .

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4.3.3
        with: 
          name: deploy-files
          path: ${{github.run_id}}.zip
  
  
  deploy:
    runs-on: ubuntu-latest
    needs: build
    
    steps:
      - uses: actions/download-artifact@v4.1.7

      - name: Create Version Date
        run: |
          echo "TIME=$(date +"%Y-%m-%d-%T")" >> $GITHUB_ENV

      - name: Deploy
        uses: einaregilsson/beanstalk-deploy@v22
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          application_name: slimekeeper
          environment_name: slimekeeper-env
          region: ${{ secrets.AWS_REGION }}
          version_label: ${{ env.TIME }}
          deployment_package: deploy-files/${{github.run_id}}.zip
